name: Maestro Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python & Poetry
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pipx ensurepath
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          pipx install poetry
          poetry self add poetry-plugin-shell
      - name: Build Maestro
        shell: bash
        run: poetry build
      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/*
          generate_release_notes: true
#      - uses: actions/upload-artifact@v4
#        with:
#          path: dist/*
#      - name: Publish to PyPi
#        uses: pypa/gh-action-pypi-publish@release/v1